# Generated by Django 5.1.2 on 2024-10-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_starting_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.course')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_student', to='accounts.student')),
            ],
        ),
    ]
