# Generated by Django 5.1.2 on 2024-10-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courseenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='price',
        ),
    ]
