# Generated by Django 5.1.2 on 2024-10-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_courseenrollment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='course_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='accounts.student'),
        ),
    ]
